### ISSUE TITLE
It's not an Issue per se. I have a G Suite and would like to archive all emails that the last email was from my domain

### ISSUE THREAD

**Issue by lucassaldanhawerneck** [hijonathan/google-scripts#13]
So I would like to archive all threads that the last email was from my own domain (no external replies).
Is it possible with minor changes on this script? 
Thanks
P.S: of course, congrats on the script!

**Comment by hijonathan** [comment]
Hey @lucassaldanhawerneck. That should be possible. I haven't tested it, but the function you'll likely want to change is [`isMe()`](https://github.com/hijonathan/google-scripts/blob/master/gmail-no-response.js#L90-L100) which determines whether the email in question was from you.

Just change the function to be something like:

```
function isMe(fromAddress) {
  return fromAddress.indexOf('@mydomain.com') > -1;
}
```

Replace `mydomain.com` with your domain, but make sure to leave the `@`. There are better ways to write this, but this should get you by.
