### ISSUE TITLE
Emails which need my response

### ISSUE THREAD

**Issue by murilop** [hijonathan/google-scripts#3]
Could you add a snippet so that instead of marking threads which I was the last one to reply, it would mark the ones which I was NOT the last one to reply?

**Comment by naikymen** [comment]
Change: ```isMe(lastFrom) && !isMe(lastTo)```

To: ```!isMe(lastFrom) && isMe(lastTo)```

 I also changed the filters to:

```
  var filters = [
    'category:primary', // 'is:sent',
    '-from:me',  // 'from:me',
    '-in:chats',
    '(-subject:"unsubscribe" AND -"This message was automatically generated by Gmail.")',
    'older_than:' + minTime,
    'newer_than:' + maxTime
  ];
```

**Comment by hijonathan** [comment]
@naikymen's solution is great and probably the right way to handle this since it's not what the script was intended to do.
