### ISSUE TITLE
Grabbing Messages with responses

### ISSUE THREAD

**Issue by CCS86** [hijonathan/google-scripts#6]
Here is what I got on my first run:

![image](https://cloud.githubusercontent.com/assets/12439543/11105210/0e20e002-8893-11e5-8534-70326cfac278.png)

**Comment by CCS86** [comment]
After looking at each, I see that I was the last to reply in each of those. Is that why they were flagged?

It would be great to distinguish between those where you replied last, and those where no reply has ever been received.

Thanks!

**Comment by hijonathan** [comment]
Hi! Yup, that's why they were flagged. This script was originally designed for sales emails where there's almost always a "next step" in the message that you want to hear back about.

You can pretty easily modify the script to only find ones in which you were the only participant. The actual filters are evaluated here: https://github.com/hijonathan/google-scripts/blob/master/gmail-no-response.js#L54-L56

**Comment by CCS86** [comment]
Cool, thanks for the reply!

Would we have to create a new variable ("justme") to evaluate in the if statement? Or can we leverage something you have evaluated already?

**Comment by hijonathan** [comment]
You have two options:

1. If you only care about threads that only had 1 email sent by you, you'd create a `justMe` variable.
2. If you wanted to find threads that were just you, but you may have sent multiple follow ups already, you'd need to loop through all messages to ensure it was really just you who participated.

That second option can be computationally expensive and potentially run over the time limit allotted for Google Scripts. It's worth trying though. To optimize it, you could loop through the messages in reverse order and break out early if you find a new respondent.

**Comment by CCS86** [comment]
Thanks Jonathan. My goal would be to find and flag threads that had one or more outgoing messages from me, but never a reply. I'm afraid that is outside my abilities to code. I am not very familiar with Goggle scripting at all!
